apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        {{- range $key, $value := .Values.kongEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - name: proxy
          containerPort: 8000
        - name: proxy-ssl
          containerPort: 8443
        - name: admin
          containerPort: 8001
        - name: admin-ssl
          containerPort: 8444
        volumeMounts:
        - name: {{ .Values.configData.name }}
          mountPath: /kong
      volumes:
      - name: {{ .Values.configData.name }}
        configMap:
          name: {{ .Values.configData.name }}

