replicaCount: 1

image:
  repository: kong
  tag: 2.7
  pullPolicy: IfNotPresent

service:
  typeAdmin: ClusterIP
  portAdmin: 8001
  portAdminSSL: 8444
  typeProxy: ClusterIP
  portProxy: 80
  portProxySSL: 443

configData:
  name: kong-config
  kongConfig: |
    _format_version: "1.1"
    services:
      - name: web-service
        url: http://hello-world.common.svc:80
        routes:
        - name: hello-world-route
          paths:
          - "/hello-world"

kongEnv:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

